resource_group_name     = "demo-webapp"
resource_group_location = "East Asia"
app_service_plan_name   = "my-appserviceplan-linux"
app_service_name        = "demo-webapp-python"
container_registry_name    = "pythondemoflaskapp"
container_image_name = "python-demo-flask-app"